os: linux
language: rust

rust:
  - 1.41.0
  - stable
  - beta
  - nightly

env:
  - FEATURES=""
  - FEATURES="--no-default-features"
  - FEATURES="--no-default-features --features \"serde-alloc\""
  - FEATURES="--no-default-features --features \"serde-std\""
  - FEATURES="--no-default-features --features \"impl-index-from\""
  - FEATURES="--no-default-features --features \"impl-index-from serde-alloc\""
  - FEATURES="--no-default-features --features \"impl-index-from serde-std\""
  - FEATURES="--all-features"

branches:
  only:
    - master

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - "! rustup default | grep -q \"stable\" || rustup component add rustfmt"
  - "! rustup default | grep -q \"stable\" || rustup component add clippy"

script:
  - eval "cargo build --verbose --all $FEATURES"
  - eval "cargo test --verbose --all $FEATURES"
  - >-
    eval "[ \"$TRAVIS_RUST_VERSION\" != \"stable\" ] || [ \"$FEATURES\" != \"\" ]
    || cargo fmt --all -- --check"
  - >-
    eval "[ \"$TRAVIS_RUST_VERSION\" != \"stable\" ]
    || cargo clippy --all $FEATURES -- -D warnings"
  - >-
    eval "[ \"$TRAVIS_RUST_VERSION\" != \"stable\" ]
    || cargo clippy --all --tests $FEATURES -- -D warnings"
