os: linux
language: rust

rust:
  - 1.41.0
  - stable
  - beta
  - nightly

branches:
  only:
    - master

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt || ! rustup default | grep -q "stable"

script:
  - cargo build --verbose --no-default-features
  - cargo build --verbose --no-default-features --features "serde-alloc"
  - cargo build --verbose --no-default-features --features "serde-std"
  - cargo build --verbose --no-default-features --features "impl-index-from"
  - cargo build --verbose --no-default-features --features "impl-index-from serde-alloc"
  - cargo build --verbose --no-default-features --features "impl-index-from serde-std"
  - cargo build --verbose --all-features
  - cargo test --verbose --no-default-features
  - cargo test --verbose --no-default-features --features "serde-alloc"
  - cargo test --verbose --no-default-features --features "serde-std"
  - cargo test --verbose --no-default-features --features "impl-index-from"
  - cargo test --verbose --no-default-features --features "impl-index-from serde-alloc"
  - cargo test --verbose --no-default-features --features "impl-index-from serde-std"
  - cargo test --verbose --all-features
  - cargo fmt -- --check
